### ISSUE TITLE
[Vue warn]: Unknown custom element: <pivot> - did you register the component correctly?

### ISSUE THREAD

**Issue by A-PASSER-BY** [line/vue-pivot-table-plus#2]
[Vue warn]: Unknown custom element: <pivot> - did you register the component correctly?
为什么会报这个错啊？明明已经引入了呀！
import { Pivot } from 'vue-pivot-table-plus'
  components: { Pivot},

**Comment by OdiljonQurbon** [comment]
Register you component like:
```
components: {
  pivot: Pivot,
},
```
